// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-tMH_03N9pDMzCyFOJ4e_jLFz8OlQ8OU',
    appId: '1:858566566430:web:527b7fd0accc8efa2a840f',
    messagingSenderId: '858566566430',
    projectId: 'social-app-9faab',
    authDomain: 'social-app-9faab.firebaseapp.com',
    databaseURL: 'https://social-app-9faab-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9faab.appspot.com',
    measurementId: 'G-66BT56ZJ0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBno-pigwcM0-OeZk0lCJCQxtGLC9Gik7E',
    appId: '1:858566566430:android:1a88a160360235682a840f',
    messagingSenderId: '858566566430',
    projectId: 'social-app-9faab',
    databaseURL: 'https://social-app-9faab-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9faab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx9PclDkKv-DX5Z-wFfGnPDS-K-7DSP6M',
    appId: '1:858566566430:ios:a5e7e47cc7a2c3bb2a840f',
    messagingSenderId: '858566566430',
    projectId: 'social-app-9faab',
    databaseURL: 'https://social-app-9faab-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9faab.appspot.com',
    androidClientId: '858566566430-7fgh43fjmlssfsd0nqfbobs423q486lg.apps.googleusercontent.com',
    iosClientId: '858566566430-kivjnucc9kji4vv4t04renahvo69722s.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialapp.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx9PclDkKv-DX5Z-wFfGnPDS-K-7DSP6M',
    appId: '1:858566566430:ios:84388c56893a34352a840f',
    messagingSenderId: '858566566430',
    projectId: 'social-app-9faab',
    databaseURL: 'https://social-app-9faab-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9faab.appspot.com',
    androidClientId: '858566566430-7fgh43fjmlssfsd0nqfbobs423q486lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-tMH_03N9pDMzCyFOJ4e_jLFz8OlQ8OU',
    appId: '1:858566566430:web:b10885a35947e48f2a840f',
    messagingSenderId: '858566566430',
    projectId: 'social-app-9faab',
    authDomain: 'social-app-9faab.firebaseapp.com',
    databaseURL: 'https://social-app-9faab-default-rtdb.firebaseio.com',
    storageBucket: 'social-app-9faab.appspot.com',
    measurementId: 'G-ZKXQ8MBKN1',
  );
}
